server:
  port: 58080
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置
  application:
    name: 论坛系统
  output:
    ansi:
      enabled: always # 开启彩色日志
  datasource:
    url: jdbc:mysql://192.168.190.131:3306/forum_db?characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式
    default-property-inclusion: NON_NULL # 不为null时序列化
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss # 显示日期格式
  level:
    root: info
    com.haifan.forum: debug
  file:
    path: D:/logs/a_project_forum
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# 项目自定义相关配置
haifan-forum:
  login:
    url: sign-in.html # 未登录状况下强制跳转页面
  index:
    board-num: 9

