server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.190.131:3306/forum?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
#  profiles:
#    active: dev
  main:
    allow-circular-references: true
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss